#!/bin/bash



validate(){

    if test -n "$1";then
        if   ! [ -r $1 ]  ;then
            echo -e "\e[41m\e[1mERROR:\e[0m\e[31m Can't read from the file specified\e[0m\n" >&2
            echo -e "\tEither the file \e[7m$1\e[27m \e[1m\e[31mdoes not exist\e[0m or is not readable"
            return 1
        fi

    else
        echo -e "\e[41m\e[1mERROR:\e[0m\e[31m No file provided\e[0m" >&2
        echo -e "\e[93mCreated by \e[5m\e[1mPranay Gupta\e[0m"
        echo -e "\e[1mUSAGE\e[0m"
        printf "\tCall the script as \e[7m./script folder\e[0m\n"
        return 1
    fi
    return 0
}

if ! validate "$1";then
    exit
fi

if ! fdupes . ;then
    echo -e "\e[41m\e[1mERROR:\e[0m\e[31m command fdupes not installed\e[0m" >&2
    printf "\tdownload with \e[7m./script sudo apt-get install fdupes\e[0m\n"
fi
dupes=`fdupes temp1`
IFS=$'\n'
read -r -d '\n' -a files <<< $dupes
count=$((0))
for file in ${files[@]}; do
    IFS='/'
    read -r -a filear <<< $file
    file2="${filear[1]}"
    if [[ $(($count %2)) -eq 0 ]];then
        IFS='
        '
        mv $file  temp2/$file2
    else 
        echo -e "\e[43m\e[30mLog:\e[0m Moving file[$count] \e[33m $file \e[0mto \e[33m  $file2\e[0m" 
    fi
    count=$(($count+1))
    
done

